export const constellations = [
    {value: "and", label: "Andromeda"},
    {value: "ant", label: "Antlia"},
    {value: "aps", label: "Apus"},
    {value: "aqr", label: "Aquarius"},
    {value: "aql", label: "Aquila"},
    {value: "ara", label: "Ara"},
    {value: "ari", label: "Aries"},
    {value: "aur", label: "Auriga"},
    {value: "boo", label: "Boötes"},
    {value: "cae", label: "Caelum"},
    {value: "cam", label: "Camelopardalis"},
    {value: "cnc", label: "Cancer"},
    {value: "cvn", label: "Canes Venatici"},
    {value: "cma", label: "Canis Major"},
    {value: "cmi", label: "Canis Minor"},
    {value: "car", label: "Carina"},
    {value: "cas", label: "Cassiopeia"},
    {value: "cen", label: "Centaurus"},
    {value: "cep", label: "Cepheus"},
    {value: "cet", label: "Cetus"},
    {value: "cha", label: "Chamaeleon"},
    {value: "cir", label: "Circinus"},
    {value: "col", label: "Columba"},
    {value: "com", label: "Coma Berenices"},
    {value: "cra", label: "Corona Austrina"},
    {value: "crb", label: "Corona Borealis"},
    {value: "crv", label: "Corvus"},
    {value: "crt", label: "Crater"},
    {value: "cru", label: "Crux"},
    {value: "cyg", label: "Cygnus"},
    {value: "del", label: "Delphinus"},
    {value: "dor", label: "Dorado"},
    {value: "dra", label: "Draco"},
    {value: "equ", label: "Equuleus"},
    {value: "eri", label: "Eridanus"},
    {value: "for", label: "Fornax"},
    {value: "gem", label: "Gemini"},
    {value: "gru", label: "Grus"},
    {value: "her", label: "Hercules"},
    {value: "hor", label: "Horologium"},
    {value: "hya", label: "Hydra"},
    {value: "hyi", label: "Hydrus"},
    {value: "ind", label: "Indus"},
    {value: "lac", label: "Lacerta"},
    {value: "leo", label: "Leo"},
    {value: "lmi", label: "Leo Minor"},
    {value: "lep", label: "Lepus"},
    {value: "lib", label: "Libra"},
    {value: "lup", label: "Lupus"},
    {value: "lyn", label: "Lynx"},
    {value: "lyr", label: "Lyra"},
    {value: "men", label: "Mensa"},
    {value: "mic", label: "Microscopium"},
    {value: "mon", label: "Monoceros"},
    {value: "mus", label: "Musca"},
    {value: "nor", label: "Norma"},
    {value: "oct", label: "Octans"},
    {value: "oph", label: "Ophiuchus"},
    {value: "ori", label: "Orion"},
    {value: "pav", label: "Pavo"},
    {value: "peg", label: "Pegasus"},
    {value: "per", label: "Perseus"},
    {value: "phe", label: "Phoenix"},
    {value: "pic", label: "Pictor"},
    {value: "psc", label: "Pisces"},
    {value: "psa", label: "Piscis Austrinus"},
    {value: "pup", label: "Puppis"},
    {value: "pyx", label: "Pyxis"},
    {value: "ret", label: "Reticulum"},
    {value: "sge", label: "Sagitta"},
    {value: "sgr", label: "Sagittarius"},
    {value: "sco", label: "Scorpius"},
    {value: "scl", label: "Sculptor"},
    {value: "sct", label: "Scutum"},
    {value: "ser", label: "Serpens Caput"},
    {value: "ser", label: "Serpens Cauda"},
    {value: "sex", label: "Sextans"},
    {value: "tau", label: "Taurus"},
    {value: "tel", label: "Telescopium"},
    {value: "tri", label: "Triangulum"},
    {value: "tra", label: "Triangulum Australe"},
    {value: "tuc", label: "Tucana"},
    {value: "uma", label: "Ursa Major"},
    {value: "umi", label: "Ursa Minor"},
    {value: "vel", label: "Vela"},
    {value: "vir", label: "Virgo"},
    {value: "vol", label: "Volans"},
    {value: "Vul", label: "Vulpecula"}
]